                                                 Basic Numpy Exercises 
                                               Compiled by: Dr. Noman Islam

#### 1. Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [2]:
import numpy as np

subdivisions = 64
start = -1.3
end = 2.5

interval = np.linspace(start, end, subdivisions)
print(interval)

[-1.3        -1.23968254 -1.17936508 -1.11904762 -1.05873016 -0.9984127
 -0.93809524 -0.87777778 -0.81746032 -0.75714286 -0.6968254  -0.63650794
 -0.57619048 -0.51587302 -0.45555556 -0.3952381  -0.33492063 -0.27460317
 -0.21428571 -0.15396825 -0.09365079 -0.03333333  0.02698413  0.08730159
  0.14761905  0.20793651  0.26825397  0.32857143  0.38888889  0.44920635
  0.50952381  0.56984127  0.63015873  0.69047619  0.75079365  0.81111111
  0.87142857  0.93174603  0.99206349  1.05238095  1.11269841  1.17301587
  1.23333333  1.29365079  1.35396825  1.41428571  1.47460317  1.53492063
  1.5952381   1.65555556  1.71587302  1.77619048  1.83650794  1.8968254
  1.95714286  2.01746032  2.07777778  2.13809524  2.1984127   2.25873016
  2.31904762  2.37936508  2.43968254  2.5       ]


#### 2. Generate an array of length  3n  filled with the cyclic pattern 1, 2, 3.

In [3]:
import numpy as np

n = 5 # Replace with desired value of n
pattern = np.array([1, 2, 3])
result = np.tile(pattern, n)
print(result)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


#### 3. Create an array of the first 10 odd integers.

In [4]:
import numpy as np

arr = np.arange(1, 20, 2)[:10]
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


#### 4. Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [5]:
import numpy as np

# Create a 10 x 10 array of zeros
arr = np.zeros((10, 10))

# Set the first and last rows and columns to 1
arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 5. Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [6]:
import numpy as np

# Create an 8 x 8 array of zeros
arr = np.zeros((8, 8), dtype=int)

# Set the odd rows and columns to 1 using slicing and striding
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
